import os
from motor.motor_asyncio import AsyncIOMotorClient

MONGO_HOST = os.getenv("REACT_APP_MONGO_HOST")
SPRINT_DB_NAME=os.getenv("REACT_APP_DB_QUIZ")
QUESTION_DB_NAME=os.getenv("REACT_APP_DB")
QUESTION_COLLECTION_NAME = os.getenv("REACT_APP_COLLECTIONS")
ISSUE_COLLECTION_NAME=os.getenv("REACT_APP_ISSUES_COLLECTIONS")
USER_COLLECTION_NAME = os.getenv("REACT_APP_USERS_COLLECTIONS")
QUIZ_COLLECTION_NAME=os.getenv("REACT_APP_QUIZ_COLLECTIONS")

client=AsyncIOMotorClient(MONGO_HOST)

SPRINT_DB=client[SPRINT_DB_NAME]
QUESTION_DB=client[QUESTION_DB_NAME]

ISSUE_COLLECTION=SPRINT_DB[ISSUE_COLLECTION_NAME]
USER_COLLECTION=SPRINT_DB[USER_COLLECTION_NAME]
QUIZ_COLLECTION=SPRINT_DB[QUIZ_COLLECTION_NAME]

QUESTION_COLLECTION=QUESTION_DB[QUESTION_COLLECTION_NAME]

